In [6]:
%matplotlib inline
import numpy as np
import matplotlib as plt

## 第一題：

題目：給定一個矩陣m，裡面的值都大於0。
請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。
m = np.array([[0,1,10],[2,6,7]])
提示：使用巢狀迴圈(nested loop)加判斷式

In [7]:
m = np.array([[0,1,10],[2,6,7]])

In [8]:
m

array([[ 0,  1, 10],
       [ 2,  6,  7]])

In [9]:
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if m[i,j] >= 1:
            m[i,j] = 1
        elif m[i,j] < 1:
            m[i,j] = 0

In [10]:
m

array([[0, 1, 1],
       [1, 1, 1]])

## 第二題：
有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
請算出班級加權平均成績，並以一個array輸出。

In [11]:
A = np.random.rand(50).reshape(10,5)*100
B = np.random.rand(50).reshape(10,5)*100
C = np.random.rand(50).reshape(10,5)*100
weights=[0.25,0.25,0.25,0.15,0.10]

In [12]:
SA = np.sum([A*weights], axis=2)
SB = np.sum([B*weights], axis=2)
SC = np.sum([C*weights], axis=2)
ALLscore = np.array([SA , SB , SC])

In [13]:
ALLscore

array([[[ 48.71327294,  70.11557166,  35.07079427,  64.21681009,
          58.62609942,  53.55033622,  59.27762492,  36.50568145,
          74.73620492,  58.84828194]],

       [[ 37.87657288,  35.02066577,  60.68608211,  76.61725104,
          50.45634792,  45.01807147,  55.71467087,  63.91338895,
          61.78904764,  53.29612072]],

       [[ 40.73139209,  65.7138112 ,  64.29058128,  59.45168677,
          31.24635416,  51.27422239,  37.77273285,  33.19730394,
          39.50348789,  43.17329411]]])

## 挑戰題一：

請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array，  
表示3個班級中30位學生的成績(小考，期中考，期末考)  。

目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績，
期末成績計算方式如下：

1. 小考20%，期中考35%，期末考45%  
2. 期中考40%，期末考60%。  
擇優作為期末成績

In [14]:
np.set_printoptions(suppress=True) #remove science notation

A = np.random.rand(270).reshape(3,30,3)*100.0
weights_1 = [0.2, 0.35, 0.45]
weights_2 = [0.0, 0.40, 0.60]

In [17]:
def Total_calc(SA, w1, w2):
    W1Sum = np.sum(SA*w1, axis = 2)
    W2Sum = np.sum(SA*w2, axis = 2)
    WTotal = np.empty(shape=[3, 30, 1])
    for i in range(3):
        for j in range(30):
           WTotal[i,j] = np.where(W1Sum[i,j] > W1Sum[i,j], W1Sum[i,j], W2Sum[i,j])
    return WTotal

In [16]:
Total_calc(A,weights_1,weights_2)

array([[[ 13.48941716],
        [ 21.57819968],
        [ 45.17614215],
        [ 62.12025097],
        [ 49.15363115],
        [ 34.97189901],
        [ 73.84563331],
        [ 57.49142604],
        [ 66.45872273],
        [ 47.72761232],
        [ 83.75341071],
        [ 36.64021228],
        [ 36.33757956],
        [ 65.71935557],
        [ 34.04772688],
        [ 45.25580141],
        [ 78.77460165],
        [ 80.6098808 ],
        [ 65.37395848],
        [ 57.95999071],
        [ 38.41624865],
        [ 53.41259862],
        [ 53.90833801],
        [ 83.42544508],
        [ 48.01329787],
        [  5.06854679],
        [ 45.86421365],
        [ 43.77901984],
        [ 32.22464567],
        [ 23.15636652]],

       [[ 12.64107272],
        [ 12.27936245],
        [ 14.48925712],
        [ 54.26708911],
        [ 50.79844718],
        [ 70.41234662],
        [ 72.06454422],
        [  5.39684476],
        [ 44.64210832],
        [ 66.48932605],
        [ 32.19900531],
        [ 84.2

## 世紀魔鬼挑戰題（做完可以直接得到一百分）：
## 美食沙漠的餐點推薦系統

### Susan是個數學高手，每天專心研究高深數學理論，因此沒有時間想每一餐要吃什麽，請依照他的需求幫他做出各餐的推薦餐點。
 
### 給定以下list:

- breakfast_list = ['古早味', '德合香', '布朗奇早餐', '星巴克', '小貓咪', '傳香飯糰', '米塔', '麥當勞', '摩斯', '7-11', '全家']
- lunch_and_dinner_list = ['小公寓', '波波恰恰', '湯饌', '享窩咖啡', '湯包', '殺人魔王', '呷麵騎士', '提洛斯', '蝴蝶漾', '東京小城', '金鰭', '樂山', 'My麵屋', '李氏餐酒館', '里克', '水煎包', '憩賢樓', '高句麗', '魯智深', '敏忠', '大正亭', '阿里郎', '鬼匠', 'Juicy Bun', '滇味廚房']
- high_price_list = ['星巴克', '摩斯', '小公寓', '享窩咖啡', '金鰭', '李氏餐酒館', '里克', 'Juicy Bun', '滇味廚房']
- snack_list = ['豆花', '政大烤場', '丐幫滷味', '鹹水雞']
 
### 請遵守以下規則：

1. 依照早餐-午餐-晚餐的順序決定
2. 餐點必須用亂數決定
3. 除了定義以上的list，不可以在其他地方出現字串
(也就是說不可以決定午餐吃'小公寓'後，另外定義dinner = ['波波恰恰', '湯饌', '享窩咖啡',...]）
4. 一天裡面只可以有一餐是屬於high_price
5. 午餐跟晚餐我不想吃同一家
6. 如果當天三餐都沒有屬於high_price的話，就要吃宵夜

### 範例輸出:
- Case 1:
早餐：古早味
午餐：提洛斯
晚餐：大正亭
宵夜：鹹水雞

- Case 2:
早餐：傳香飯糰
午餐：小公寓
晚餐：鬼匠

In [2]:
-


早餐: 德合香
午餐: 鬼匠
晚餐: 敏忠
消夜: 鹹水雞


In [3]:
give_me_food(breakfast_list, lunch_and_dinner_list, high_price_list, snack_list)

早餐: 摩斯
午餐: 蝴蝶漾
晚餐: 呷麵騎士


In [4]:
give_me_food(breakfast_list, lunch_and_dinner_list, high_price_list, snack_list)

早餐: 小貓咪
午餐: 李氏餐酒館
晚餐: My麵屋


In [5]:
give_me_food(breakfast_list, lunch_and_dinner_list, high_price_list, snack_list)

早餐: 全家
午餐: 憩賢樓
晚餐: 李氏餐酒館
